AlmaLinux
CENTOS ,AlmaLinux ,Ubuntu ,ZionLinux Working

diff --git a/AlmaLinux b/AlmaLinux
--- a/AlmaLinux
+++ b/AlmaLinux
@@ -38,7 +38,7 @@ echo -e "${jeshile} ?            Checking OS Version          ? \e[0m"
 echo -e "${jeshile} ???????????????????????????????????????????????? \e[0m"
 echo " " 
 
-if [ "$osname" == "Ubuntu"  ] || [ "$osname" == "AlmaLinux"  ]  ||  [ "$osname" == "Zorin"  ] ; then
+if [ "$osname" == "Ubuntu"  ] || [ "$osname" == "AlmaLinux"  ]  ||  [ "$osname" == "Zorin"  ]| [ "$osname" == "CentOS"  ]  | ; then
 echo -e "${jeshile} ???????????????????????????????????????????????? \e[0m"
 echo -e "${jeshile} ?             Support System                   ? \e[0m"
 echo -e "${jeshile} ???????????????????????????????????????????????? \e[0m"
@@ -555,5 +555,237 @@ reboot
 else
 echo " "   	
 fi 
+if [ "$osname" == "AlmaLinux" ]; then
+yum remove  -y httpd
+yum istall  -y wget
+yum -y install libxml2 libxml2-devel
+yum -y install bzip2 bzip2-devel
+yum -y install curl-devel
+yum -y install libjpeg-turbo-devel
+yum -y install libpng-devel
+yum -y install freetype-devel
+yum -y install epel-release
+yum -y install uw-imap-devel libc-client
+yum -y install postgresql-devel
+yum -y install libxslt.x86_64 libxslt-devel.x86_64
+yum -y install llibssh2-devel
+yum -y install autoconf
+yum -y install pcre-devel
+yum -y install git libssh2-devel gcc-c++
+yum install -y libzip-devel
+if [[ $osrelease  = "7."* ]] ; then 
+yum install https://github.com/lemp-info/lemp/raw/master/oniguruma-5.9.5-3.el7.x86_64.rpm -y
+yum install https://github.com/lemp-info/lemp/raw/master/oniguruma-devel-5.9.5-3.el7.x86_64.rpm -y
+cd /root
+yum remove -y libzip
+wget https://github.com/lemp-info/lemp/raw/master/script/libzip-1.2.0.tar.gz  -P /root
+#wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=1QzWUFvZ6QCaHISVyOEsgrxlW9bm7LaMR" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1QzWUFvZ6QCaHISVyOEsgrxlW9bm7LaMR" -O /roor/libzip-1.2.0.tar.gz  && rm -rf /tmp/cookies.txt
+tar -zxvf libzip-1.2.0.tar.gz
+cd libzip-1.2.0
+./configure
+sleep 1
+make && make install
+sleep 2
+echo '/usr/local/lib64
+/usr/local/lib
+/usr/lib
+/usr/lib64'>>/etc/ld.so.conf
+rm -r -f /root/ibzip-1.2.0.tar.gz
+rm -r -f /root/ibzip-1.2.0
+yum install -y libzip-devel
+fi
+if [[ $osrelease  = "8."* ]] ; then 
+yum install https://github.com/lemp-info/lemp/raw/master/oniguruma-6.8.2-1.el8.x86_64.rpm -y
+fi
+while true; do
+wget https://github.com/lemp-info/lemp/raw/master/script/lemp-CentOS.tar.gz -P /home/lemp
+sleep 1
+ [ -f /home/lemp/lemp-CentOS.tar.gz ] && break
+done
+#wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=1nF3EdYIVzNc4Hos2zzfR_XTj1vshPgtd" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1nF3EdYIVzNc4Hos2zzfR_XTj1vshPgtd" -O /home/lemp/lemp-CentOS.tar.gz  && rm -rf /tmp/cookies.txt
+tar -xvzf  /home/lemp/lemp-CentOS.tar.gz -C /home/lemp
+rm -rf /home/lemp/lemp-CentOS.tar.gz
+sudo chmod -R 755 /home/lemp/start-stop-daemon
+mv /home/lemp/start-stop-daemon /usr/sbin/
+if [ $MariaDB != "y" ];then
+rm -rf /home/lemp/script/mysql.server
+fi
+sudo chmod -R 755 /home/lemp/script/*
+cp /home/lemp/script/mysql.server /etc/rc.d/init.d/
+mv /home/lemp/script/* /etc/rc.d/rc0.d/
 
+if [[ $osrelease  = "7."* ]] ; then 
+while true; do
+ wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=12Aij97O48EH4C14yH_CVQ3yV2ECxh6Og" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=12Aij97O48EH4C14yH_CVQ3yV2ECxh6Og" -O /home/lemp/lempCentOS7PHP.tar.gz  && rm -rf /tmp/cookies.txt
+ sleep 1
+ [ -f /home/lemp/lempCentOS7PHP.tar.gz ] && break
+done
+sudo chmod -R 755 /home/lemp/lempCentOS7PHP.tar.gz
+tar -xvzf /home/lemp/lempCentOS7PHP.tar.gz -C /home/lemp/
+rm -rf /home/lemp/lempCentOS7PHP.tar.gz
+fi
+
+if [[ $osrelease  = "8."* ]] ; then 
+while true; do
+ wget --load-cookies /tmp/cookies_lempCentOS8PHP.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies_lempCentOS8PHP.txt --keep-session-cookies --no-check-certificate "https://docs.google.com/uc?export=download&id=1k05pv6PIfn0TcgJk5jXyWrqYrI0LtXEF" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1k05pv6PIfn0TcgJk5jXyWrqYrI0LtXEF" -O /home/lemp/lempCentOS8PHP.tar.gz  && rm -rf /tmp/cookies_lempCentOS8PHP.txt
+ sleep 1
+ [[ ! -f /tmp/cookies_lempCentOS8PHP.txt ]] && break
+done
+sudo chmod -R 755 /home/lemp/lempCentOS8PHP.tar.gz
+tar -xvzf /home/lemp/lempCentOS8PHP.tar.gz -C /home/lemp/
+rm -rf /home/lemp/lempCentOS8PHP.tar.gz
+yum install -y openssl-devel
+fi
+fi
+
+sudo mv /home/lemp/phpmyadmin/phpmyadmin.sql /home/lemp/
+sudo mv /home/lemp/phpmyadmin/config.inc.php /home/lemp/
+sudo rm -rf /home/lemp/phpmyadmin
+sleep 1
+while true; do
+sudo wget https://github.com/lemp-info/lemp/raw/master/phpmyadmin/phpMyAdmin-5.0.2-all-languages.tar.gz -P /home/lemp/ 
+sleep 1
+ [ -f /home/lemp/phpMyAdmin-5.0.2-all-languages.tar.gz ] && break
+done
+sleep 1
+sudo chmod -R 755 /home/lemp/phpMyAdmin-5.0.2-all-languages.tar.gz
+sleep 1
+sudo tar -xvzf /home/lemp/phpMyAdmin-5.0.2-all-languages.tar.gz -C /home/lemp/
+sleep 0
+sudo rm -rf /home/lemp/phpMyAdmin-5.0.2-all-languages.tar.gz
+sudo mv /home/lemp/phpMyAdmin-5.0.2-all-languages /home/lemp/phpmyadmin
+sudo mv /home/lemp/phpmyadmin.sql /home/lemp/phpmyadmin/
+sudo mv /home/lemp/config.inc.php /home/lemp/phpmyadmin/
+sudo mkdir /home/lemp/phpmyadmin/tmp
+
+if [ $MariaDB = "y" ];then
+while true; do
+sudo wget https://archive.mariadb.org//mariadb-10.5.0/bintar-linux-systemd-x86_64/mariadb-10.5.0-linux-systemd-x86_64.tar.gz -P /home/lemp/ 
+sleep 1
+[ -f /home/lemp/mariadb-10.5.0-linux-systemd-x86_64.tar.gz ] && break
+done
+sudo tar -xvf /home/lemp/mariadb-10.5.0-linux-systemd-x86_64.tar.gz -C /home/lemp 
+sudo mv  /home/lemp/mariadb-10.5.0-linux-systemd-x86_64 /home/lemp/mysql
+sudo rm -rf /home/lemp/mariadb-10.5.0-linux-systemd-x86_64.tar.gz
+sudo rm -rf /home/lemp/mysql/support-files/mysql.server
+sudo chmod -R 755 /etc/init.d/mysql.server
+sudo cp /etc/init.d/mysql.server /home/lemp/mysql/support-files/
+sudo chmod -R 755 /home/lemp
+sudo chmod -R 755 /home/lemp/mysql
+sleep 1
+export PATH=/home/lemp/mysql/bin:$PATH
+sleep 1
+sudo chown -R mysql.mysql /home/lemp/mysql
+sudo rm -rf /home/lemp/mysql/data
+sleep 1
+sudo /home/lemp/mysql/scripts/mysql_install_db --user=mysql --basedir=/home/lemp/mysql/ --datadir=/home/lemp/mysql/data
+echo -e " \n "
+sleep 1
+#sudo /home/lemp/mysql/bin/mysqld_safe --user=mysql --basedir=/home/lemp/mysql/ --datadir=/home/lemp/mysql/data &
+echo -e " \n "
+sleep 1
+sudo ln -s /home/lemp/mysql/bin/* /usr/local/bin/
+sleep 1
+sudo mv /etc/my.cnf /etc/my.cnf-old
+sleep 1
+sudo chmod -R 755 /home/lemp/mysql/support-files/mysql.server
+sleep 1
+ sudo chown -R  mysql:mysql /home/lemp/mysql
+ sleep 1
+sudo /home/lemp/mysql/support-files/mysql.server start
+sleep 1
+sudo /home/lemp/mysql/bin/mysqladmin -u root password "$SQL"
+sleep 1
+mysql -uroot -p"$SQL" -e "CREATE DATABASE phpmyadmin"  
+mysql -uroot -p"$SQL" phpmyadmin < /home/lemp/phpmyadmin/phpmyadmin.sql 
+fi
+
+if [ "$osname" == "Ubuntu" ] || [ "$osname" == "Zorin"  ] ; then
+if [ -f "$file" ]
+then
+sed --in-place '/exit 0/d' /etc/rc.local 
+echo "sleep 2" >> /etc/rc.local
+echo "sudo /etc/init.d/lemp start" >> /etc/rc.local
+echo "exit 0" >> /etc/rc.local
+else 
+echo "#!/bin/sh -e" >> /etc/rc.local
+echo "#">> /etc/rc.local
+echo "# rc.local">> /etc/rc.local
+echo "#">> /etc/rc.local
+echo "# This script is executed at the end of each multiuser runlevel." >> /etc/rc.local
+echo "# value on error." >> /etc/rc.local
+echo "#" >> /etc/rc.local
+echo "# In order to enable or disable this script just change the execution" >> /etc/rc.local
+echo "# bits." >> /etc/rc.local
+echo "#" >> /etc/rc.local
+echo "# By default this script does nothing." >> /etc/rc.local
+echo -e " \n " >> /etc/rc.local
+echo "sleep 2" >> /etc/rc.local
+echo "sudo /etc/init.d/lemp start" >> /etc/rc.local
+echo "exit 0" >> /etc/rc.local
+sleep 1
+ 
+sudo chmod +x /etc/rc.local  
+fi
+sudo rm -r /home/lemp/openssl-1.1.1c > /dev/null 2>&1
+sudo rm -r /home/lemp/openssl-1.1.1c.tar.gz > /dev/null 2>&1
+sudo sudo /etc/init.d/lemp start
+fi
+
+if [ "$osname" == "CentOS" ]; then
+if [ $file2 -eq 1 ]; then
+echo " "   
+else
+echo "/etc/rc.d/rc0.d/lemp start" >> /etc/rc.local
+fi
+chmod +x /etc/rc.local
+sudo /etc/rc.d/rc0.d/lemp start
+fi
+
+sed -i 's/50x.html/50x.php/g' /home/lemp/nginx/conf/nginx.conf
+sleep 1
+sudo chmod 755 /home/lemp/phpmyadmin/tmp
+sudo chmod 777 /home/lemp/phpmyadmin/tmp 
+sudo chmod 755 /home/lemp/phpmyadmin/config.inc.php
+sleep 2
+sudo rm -rf /home/lemp/www/*
+while true; do
+sudo wget  https://github.com/lemp-info/lemp/raw/master/script/lempweb.tar.gz -P /home/lemp/www 
+sleep 1
+ [ -f /home/lemp/www/lempweb.tar.gz ] && break
+done
+sleep 1
+sudo tar -xvf /home/lemp/www/lempweb.tar.gz -C /home/lemp/www
+sudo rm -rf /home/lemp/www/lempweb.tar.gz
+sudo ln -s /home/lemp/phpmyadmin /home/lemp/www/phpmyadmin
+
+
+if [ $MariaDB != "y" ]; then
+if [ $mysqlstatus = "y" ]; then
+if (whiptail --title "database phpmyadmin." --yesno "Do you want to install database phpmyadmin ?" 8 78); then   
+phpmyadmin="y"
+else
+phpmyadmin="n"	 
+fi 
+if [ $phpmyadmin = "y" ];then
+while true; do
+ echo 
+mysqlpassword=$(whiptail --title "MariaDB Password" --passwordbox "Please enter your mysql password." 10 60 3>&1 1>&2 2>&3)
+ echo 
+RESULT=`mysqlshow --user=root --password=$mysqlpassword mysql | grep -v Wildcard | grep -o mysql `
+[ "$RESULT" = "mysql" ] && break
+done
+mysql -uroot -p"$mysqlpassword" -e "CREATE DATABASE phpmyadmin"  
+mysql -uroot -p"$mysqlpassword" phpmyadmin < /home/lemp/phpmyadmin/phpmyadmin.sql 
+fi 
+fi
+fi
+sudo chown lemp:lemp /home/lemp
+sudo chown lemp:lemp /home/lemp/*
+sudo chown -R mysql.mysql /home/lemp/mysql
+if (whiptail --title "Restart." --yesno "Do you want to restart now ?" 8 78); then   
+reboot
+else
+echo " "   	
+fi 
 exit 1
